# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 718)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 718))
        MainWindow.setMaximumSize(QtCore.QSize(1280, 718))
        MainWindow.setStyleSheet(
            "#joint_1,#joint_2,#joint_3,#joint_4,#joint_5,#joint_6,#joint_1,#joint_7,#joint_8,#joint_9,#joint_10,#joint_11,#joint_12,#joint_13,#joint_14,#joint_15,#joint_16,#joint_17,#joint_18{\n"
            "    background-color: rgb(0, 0, 0);\n"
            "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#Foot_1,#Foot_2,#Foot_3,#Foot_4,#Foot_5,#Foot_6{\n"
                                         "background-color: rgb(85, 85, 127);\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.Foot_1Image = QtWidgets.QLabel(self.centralwidget)
        self.Foot_1Image.setGeometry(QtCore.QRect(90, 10, 160, 160))
        self.Foot_1Image.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.Foot_1Image.setObjectName("Foot_1Image")
        self.Foot_6Image = QtWidgets.QLabel(self.centralwidget)
        self.Foot_6Image.setGeometry(QtCore.QRect(90, 190, 160, 160))
        self.Foot_6Image.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.Foot_6Image.setObjectName("Foot_6Image")
        self.Foot_3Image = QtWidgets.QLabel(self.centralwidget)
        self.Foot_3Image.setGeometry(QtCore.QRect(790, 190, 160, 160))
        self.Foot_3Image.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.Foot_3Image.setObjectName("Foot_3Image")
        self.Foot_4Image = QtWidgets.QLabel(self.centralwidget)
        self.Foot_4Image.setGeometry(QtCore.QRect(790, 370, 160, 160))
        self.Foot_4Image.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.Foot_4Image.setObjectName("Foot_4Image")
        self.Foot_2Image = QtWidgets.QLabel(self.centralwidget)
        self.Foot_2Image.setGeometry(QtCore.QRect(790, 10, 160, 160))
        self.Foot_2Image.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.Foot_2Image.setObjectName("Foot_2Image")
        self.Foot_5Image = QtWidgets.QLabel(self.centralwidget)
        self.Foot_5Image.setGeometry(QtCore.QRect(90, 370, 160, 160))
        self.Foot_5Image.setStyleSheet("background-color: rgb(85, 85, 127);")
        self.Foot_5Image.setObjectName("Foot_5Image")
        self.SpiderImage = QtWidgets.QLabel(self.centralwidget)
        self.SpiderImage.setGeometry(QtCore.QRect(260, 10, 520, 520))
        self.SpiderImage.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.SpiderImage.setObjectName("SpiderImage")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 550, 1251, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 570, 1241, 121))
        self.textBrowser.setObjectName("textBrowser")
        self.leg1label = QtWidgets.QLabel(self.centralwidget)
        self.leg1label.setGeometry(QtCore.QRect(150, 170, 54, 12))
        self.leg1label.setObjectName("leg1label")
        self.leg6lable = QtWidgets.QLabel(self.centralwidget)
        self.leg6lable.setGeometry(QtCore.QRect(150, 350, 54, 12))
        self.leg6lable.setObjectName("leg6lable")
        self.leg5label = QtWidgets.QLabel(self.centralwidget)
        self.leg5label.setGeometry(QtCore.QRect(150, 530, 54, 12))
        self.leg5label.setObjectName("leg5label")
        self.leg2label = QtWidgets.QLabel(self.centralwidget)
        self.leg2label.setGeometry(QtCore.QRect(850, 170, 54, 12))
        self.leg2label.setObjectName("leg2label")
        self.leg3label = QtWidgets.QLabel(self.centralwidget)
        self.leg3label.setGeometry(QtCore.QRect(850, 350, 41, 16))
        self.leg3label.setObjectName("leg3label")
        self.leg4label = QtWidgets.QLabel(self.centralwidget)
        self.leg4label.setGeometry(QtCore.QRect(850, 530, 54, 12))
        self.leg4label.setObjectName("leg4label")
        self.joint_1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_1.setGeometry(QtCore.QRect(23, 40, 50, 23))
        self.joint_1.setDigitCount(3)
        self.joint_1.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.joint_1.setProperty("intValue", 0)
        self.joint_1.setObjectName("joint_1")
        self.joint_7 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_7.setGeometry(QtCore.QRect(23, 80, 50, 23))
        self.joint_7.setDigitCount(3)
        self.joint_7.setObjectName("joint_7")
        self.joint_13 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_13.setGeometry(QtCore.QRect(23, 120, 50, 23))
        self.joint_13.setDigitCount(3)
        self.joint_13.setObjectName("joint_13")
        self.joint_12 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_12.setGeometry(QtCore.QRect(23, 260, 51, 23))
        self.joint_12.setSmallDecimalPoint(False)
        self.joint_12.setDigitCount(3)
        self.joint_12.setMode(QtWidgets.QLCDNumber.Dec)
        self.joint_12.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.joint_12.setProperty("value", 100.0)
        self.joint_12.setObjectName("joint_12")
        self.joint_18 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_18.setGeometry(QtCore.QRect(23, 300, 51, 23))
        self.joint_18.setSmallDecimalPoint(False)
        self.joint_18.setDigitCount(3)
        self.joint_18.setMode(QtWidgets.QLCDNumber.Dec)
        self.joint_18.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.joint_18.setProperty("value", 100.0)
        self.joint_18.setObjectName("joint_18")
        self.joint_6 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_6.setGeometry(QtCore.QRect(23, 220, 51, 23))
        self.joint_6.setLineWidth(1)
        self.joint_6.setSmallDecimalPoint(False)
        self.joint_6.setDigitCount(3)
        self.joint_6.setMode(QtWidgets.QLCDNumber.Dec)
        self.joint_6.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.joint_6.setProperty("value", 100.0)
        self.joint_6.setObjectName("joint_6")
        self.joint_11 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_11.setGeometry(QtCore.QRect(23, 440, 51, 23))
        self.joint_11.setDigitCount(3)
        self.joint_11.setObjectName("joint_11")
        self.joint_17 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_17.setGeometry(QtCore.QRect(23, 480, 51, 23))
        self.joint_17.setDigitCount(3)
        self.joint_17.setObjectName("joint_17")
        self.joint_5 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_5.setGeometry(QtCore.QRect(23, 400, 51, 23))
        self.joint_5.setDigitCount(3)
        self.joint_5.setObjectName("joint_5")
        self.joint_8 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_8.setGeometry(QtCore.QRect(960, 80, 50, 23))
        self.joint_8.setDigitCount(3)
        self.joint_8.setObjectName("joint_8")
        self.joint_14 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_14.setGeometry(QtCore.QRect(960, 120, 50, 23))
        self.joint_14.setDigitCount(3)
        self.joint_14.setObjectName("joint_14")
        self.joint_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_2.setGeometry(QtCore.QRect(960, 40, 50, 23))
        self.joint_2.setDigitCount(3)
        self.joint_2.setObjectName("joint_2")
        self.joint_9 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_9.setGeometry(QtCore.QRect(960, 260, 50, 23))
        self.joint_9.setDigitCount(3)
        self.joint_9.setObjectName("joint_9")
        self.joint_15 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_15.setGeometry(QtCore.QRect(960, 300, 50, 23))
        self.joint_15.setDigitCount(3)
        self.joint_15.setObjectName("joint_15")
        self.joint_3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_3.setGeometry(QtCore.QRect(960, 220, 50, 23))
        self.joint_3.setDigitCount(3)
        self.joint_3.setObjectName("joint_3")
        self.joint_10 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_10.setGeometry(QtCore.QRect(960, 440, 50, 23))
        self.joint_10.setDigitCount(3)
        self.joint_10.setObjectName("joint_10")
        self.joint_16 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_16.setGeometry(QtCore.QRect(960, 480, 50, 23))
        self.joint_16.setDigitCount(3)
        self.joint_16.setObjectName("joint_16")
        self.joint_4 = QtWidgets.QLCDNumber(self.centralwidget)
        self.joint_4.setGeometry(QtCore.QRect(960, 400, 50, 23))
        self.joint_4.setDigitCount(3)
        self.joint_4.setObjectName("joint_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1050, 30, 211, 321))
        self.groupBox.setObjectName("groupBox")
        self.PanControllerVertial = QtWidgets.QSlider(self.groupBox)
        self.PanControllerVertial.setGeometry(QtCore.QRect(100, 40, 22, 121))
        self.PanControllerVertial.setMaximum(90)
        self.PanControllerVertial.setProperty("value", 45)
        self.PanControllerVertial.setOrientation(QtCore.Qt.Vertical)
        self.PanControllerVertial.setObjectName("PanControllerVertial")
        self.PanControllerHorizon = QtWidgets.QSlider(self.groupBox)
        self.PanControllerHorizon.setGeometry(QtCore.QRect(50, 200, 121, 22))
        self.PanControllerHorizon.setMinimum(0)
        self.PanControllerHorizon.setMaximum(180)
        self.PanControllerHorizon.setProperty("value", 90)
        self.PanControllerHorizon.setOrientation(QtCore.Qt.Horizontal)
        self.PanControllerHorizon.setTickInterval(0)
        self.PanControllerHorizon.setObjectName("PanControllerHorizon")
        self.ChangeDisplay = QtWidgets.QPushButton(self.groupBox)
        self.ChangeDisplay.setGeometry(QtCore.QRect(10, 250, 91, 23))
        self.ChangeDisplay.setObjectName("ChangeDisplay")
        self.AddYolo = QtWidgets.QPushButton(self.groupBox)
        self.AddYolo.setGeometry(QtCore.QRect(110, 250, 91, 23))
        self.AddYolo.setObjectName("AddYolo")
        self.TakePhoto = QtWidgets.QPushButton(self.groupBox)
        self.TakePhoto.setGeometry(QtCore.QRect(10, 280, 191, 23))
        self.TakePhoto.setObjectName("TakePhoto")
        self.PanVertialValue = QtWidgets.QLCDNumber(self.groupBox)
        self.PanVertialValue.setGeometry(QtCore.QRect(130, 40, 50, 23))
        self.PanVertialValue.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.PanVertialValue.setDigitCount(3)
        self.PanVertialValue.setObjectName("PanVertialValue")
        self.PanHorizonValue = QtWidgets.QLCDNumber(self.groupBox)
        self.PanHorizonValue.setGeometry(QtCore.QRect(130, 170, 50, 23))
        self.PanHorizonValue.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.PanHorizonValue.setDigitCount(3)
        self.PanHorizonValue.setObjectName("PanHorizonValue")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1050, 360, 211, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.stop = QtWidgets.QPushButton(self.groupBox_2)
        self.stop.setGeometry(QtCore.QRect(90, 70, 41, 41))
        self.stop.setObjectName("stop")
        self.turn_left = QtWidgets.QPushButton(self.groupBox_2)
        self.turn_left.setGeometry(QtCore.QRect(40, 70, 41, 41))
        self.turn_left.setObjectName("turn_left")
        self.turn_right = QtWidgets.QPushButton(self.groupBox_2)
        self.turn_right.setGeometry(QtCore.QRect(140, 70, 41, 41))
        self.turn_right.setObjectName("turn_right")
        self.back = QtWidgets.QPushButton(self.groupBox_2)
        self.back.setGeometry(QtCore.QRect(90, 120, 41, 41))
        self.back.setObjectName("back")
        self.forward = QtWidgets.QPushButton(self.groupBox_2)
        self.forward.setGeometry(QtCore.QRect(90, 20, 41, 41))
        self.forward.setObjectName("forward")
        self.LinkDetector = QtWidgets.QTextBrowser(self.centralwidget)
        self.LinkDetector.setGeometry(QtCore.QRect(260, 10, 171, 41))
        self.LinkDetector.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.LinkDetector.setFrameShape(QtWidgets.QFrame.Box)
        self.LinkDetector.setLineWidth(0)
        self.LinkDetector.setObjectName("LinkDetector")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "六足机器人客户端软件"))
        self.Foot_1Image.setText(_translate("MainWindow", "TextLabel"))
        self.Foot_6Image.setText(_translate("MainWindow", "TextLabel"))
        self.Foot_3Image.setText(_translate("MainWindow", "TextLabel"))
        self.Foot_4Image.setText(_translate("MainWindow", "TextLabel"))
        self.Foot_2Image.setText(_translate("MainWindow", "TextLabel"))
        self.Foot_5Image.setText(_translate("MainWindow", "TextLabel"))
        self.SpiderImage.setText(_translate("MainWindow", "TextLabel"))
        self.leg1label.setText(_translate("MainWindow", "关节一"))
        self.leg6lable.setText(_translate("MainWindow", "关节六"))
        self.leg5label.setText(_translate("MainWindow", "关节五"))
        self.leg2label.setText(_translate("MainWindow", "关节二"))
        self.leg3label.setText(_translate("MainWindow", "关节三"))
        self.leg4label.setText(_translate("MainWindow", "关节四"))
        self.groupBox.setTitle(_translate("MainWindow", "云台控制器"))
        self.ChangeDisplay.setText(_translate("MainWindow", "切换主窗口显示"))
        self.AddYolo.setText(_translate("MainWindow", "启用Yolo检测"))
        self.TakePhoto.setText(_translate("MainWindow", "拍照 Space"))
        self.groupBox_2.setTitle(_translate("MainWindow", "指令控制器"))
        self.stop.setText(_translate("MainWindow", "停止P"))
        self.turn_left.setText(_translate("MainWindow", "左转A"))
        self.turn_right.setText(_translate("MainWindow", "右转D"))
        self.back.setText(_translate("MainWindow", "后退S"))
        self.forward.setText(_translate("MainWindow", "前进W"))
